### PR TITLE
A11y Enhancements

### PR DESCRIPTION
**Pull request by BrianSipple**
After digging into the project for a bit, I've come up with a few ideas for improving the accessibility of our elements to users with assistive devices.

For one, we can allow users to specify a [table caption](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) -- as well as its alignment -- at the root level, and then place/align a `<caption>` element just after the `<table>` element that we render.

We can also allow columns to have a `scope` attribute. [This article provides a good description](http://webaim.org/techniques/tables/data#scope), but essentially, when table structures start to get a bit complex, having a `scope` attribute on `th` elements gives screen readers an unambiguous declaration of how that `th` is supposed to fit in to the puzzle.

### CODE REVIEW

**Comment by cball** [comment]
This seems like a good approach. Is there a standard way to have assistive devices leverage the caption but hide it otherwise?

Could you squash these commits down?

**Comment by BrianSipple** [comment]
@cball There is. It's the old-fashioned "visually hidden" pattern, which [WebAIM currently recommends](http://webaim.org/techniques/css/invisiblecontent/#absolutepositioning) implementing like so:

``` css
.visually-hidden {
  position:absolute;
  left:-10000px;
  top:auto;
  width:1px;
  height:1px;
  overflow:hidden;
}
```

I updated (and squashed the commits while I was at it) to allow [support for a `hideCaption` attribute](https://github.com/cball/justa-table/pull/106/files#diff-de9a93fc4113a51e044f280e5f066da2R79) on the table, which then gets passed to the caption component, which [has a `classNameBinding`](https://github.com/cball/justa-table/pull/106/files#diff-08be660f8bb49f0c642a683953eae9a0R9) on a `hideFromView` property that gives it the above styling. The `basic-table` example in the demo now has a toggle button that demonstrates its use.

**Comment by BrianSipple** [comment]
One more note: I noticed that with the update to Ember 2.7, and the need to start using `rootURL`, we [missed a spot](https://github.com/cball/justa-table/blob/master/tests/dummy/app/index.html#L12) in the dummy app's `index.html`. It seemed relatively harmless to slide that fix into this PR as I was making updates to the demo, but I could certainly break it out if you'd like it to be separate.

**Comment by cball** [comment]
No worries, this is great. Thanks so much for helping address this.

**Pull request merged**
